version: '3.9'

services:
  # mongodb services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  # node api service
  api:
    build: .
    ports: 
      - 4000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://root:uOv4YA8lvsrFbjPR@cluster0.wjaxi.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: testCollection
      DB_USER: root
      DB_PASS: uOv4YA8lvsrFbjPR
      NAME: IBSANJU
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}